### ISSUE TITLE
Web form in not displaying when deployed to TEAM Engine

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-sta10#1]
The web form is to start the test is not displaying

The following error is reporte
```
SEVERE: 
java.lang.Exception: Error: Suite {http://www.opengis.net/cite/sta10}ets-sta10-0.1-SNAPSHOT not found.
	at com.occamlab.te.TECore.execute_suite(TECore.java:409)
	at com.occamlab.te.TECore.execute(TECore.java:295)
	at com.occamlab.te.TECore.run(TECore.java:2276)
	at java.lang.Thread.run(Thread.java:745)

```

Typing rest suites, this is shown:
http://localhost:8080/teamengine/rest/suites/sta10/0.1-SNAPSHOT/

**Comment by rjmartell** [comment]
This error was logged in teamengine-*.log: 

    Error: Suite {http://www.opengis.net/cite/sta10}ets-sta10-0.1-SNAPSHOT not found

In the CTL wrapper script (sta10-suite.ctl), the suite name has a fixed version of "1.0" instead of the ${version} parameter.
