### ISSUE TITLE
Invalid encoding type values

### ISSUE THREAD

**Issue by tebben** [opengeospatial/ets-sta10#16]
In different create-update-delete tests unknown encoding types are used, for instance the method putEntities in Capability2Test.java:
Location.encodingType: "UPDATED ENCODING"
Sensor.encodingType: "http://schema.org/description"
FeatureOfInterest.encodingType: "SQUARE"

The documentation describes:
- Location: The encoding type of the Location property. Its value is one of the ValueCode enumeration (see Table 8-6).
- Sensor: The encoding type of the metadata property. Its value is one of the ValueCode enumeration (see Table 8-14 for the available ValueCode).
- FeatureOfInterest: The encoding type of the feature property. Its value is one of the ValueCode enumeration (see Table 8-6 for the available ValueCode).

**Table 8-6**
GeoJSON	- application/vnd.geo+json

**Table 8-14**
PDF - application/pdf
SensorML - http://www.opengis.net/doc/IS/SensorML/2.0

Scratchpad is accepting non described encoding types and the sensorup docs (http://www.sensorup.com/docs/) is giving POST examples with unknown encoding types. Can someone explain this? Should we just accept any encoding string or return an error when the encoding type is not supported by the entity type as described in the docs?

**Comment by bermud** [comment]
@taniakhalafbeigi, can you please explain further and do we need to change anything in the test?

**Comment by liangsteve** [comment]
@tebben  You are right.  The test needs to be updated to use only the values of the Value Code list.  Good catch.

**Comment by taniakhalafbeigi** [comment]
The code is updated. Thanks for reporting the problem.
