### ISSUE TITLE
Add conformance class configuration into the sta10 test.

### ISSUE THREAD

**Issue by keshav-nangare** [opengeospatial/ets-sta10#38]
The test needs to be updated to better provide information about the grouping of the conformance class and determination about which ones are the basic conformance classes needed for certification.

Changes that are required are described here:

https://github.com/opengeospatial/cite/wiki/Encoding-Conformance-Classes

**Comment by dstenger** [comment]
Solved by https://github.com/opengeospatial/ets-sta10/commit/872b22cf1cf886d535ce8e84ad3e439e90117c2d.
