### ISSUE TITLE
Testing optional features like PUT

### ISSUE THREAD

**Issue by hylkevds** [opengeospatial/ets-sta10#41]
Commit 877beb0ba6da5c42f314244f9669d52f82c64a22 removes the tests for PUT. However A.3.1.2 Test: Sensing Entity Update states 
> (Where applicable) For each SensorThings entity type send an update request with PUT, check if the service responds as defined in Section 10.3.

So if a service implements PUT, it should be tested if it implements it correctly.
Instead of removing the test, a check should be added at the start of the test, to see if the service supports PUT. If not, the rest of the test can be skipped. If it does support PUT, the test should continue.

In general, I think this approach should be taken for all optional features.

**Comment by taniakhalafbeigi** [comment]
The whole test suite is aiming to test only the conformance of the service under test to SensorThings API and not testing the whole system. Testing the whole system can be huge and very time consuming specially when run from TEAM Engine and also it is not the goal of conformance test suite.
We can have another level of testing for testing those optional features, but I think at least it should not be part of our level 2 testing for the above mentioned reasons.

**Comment by hylkevds** [comment]
As I quoted, at least PUT is explicitly mentioned as part of the requirements for conformance, and thus should be tested, in level 2.

For other optional features, that are not explicitly mentioned in the requirements, adding a separate level sounds like a good idea. We might need more than one level ;)

Would the tasking part also go into the same test suite, or does that get its own test suite?

**Comment by taniakhalafbeigi** [comment]
The test shouldn't have been in conformance classes in the first place and it needs to be removed from conformance classes as also mentioned in sensorthings github. 
We will use the same code in the optional part later.

**Comment by hylkevds** [comment]
Ah, so it is: https://github.com/opengeospatial/sensorthings/issues/10
That's where linking to issues in commit messages is helpful.

**Comment by taniakhalafbeigi** [comment]
Thanks. I was on phone and didn't give me option to link, intended to do that in the morning but thanks for linking that already.
