### ISSUE TITLE
 An Exception occurred during testing!: JSONObject<br>["@iot.id"] is not a number.

### ISSUE THREAD

**Issue by Abouzeid** [opengeospatial/ets-sta10#42]
I am running the STA test. I am getting the Error:
`java.lang.AssertionError: An Exception occurred during testing!: JSONObject<br>["@iot.id"] is not a number.`

All my entities' ids are "Guid/uuid" data-type. 
I've found in the code below that the ids are expected to be **List** of Long or convertible to "long". Therefore, the conversion from "Guid" to "long" raised the exception.
```
private void readRelatedEntityOfEntityWithEntityType(EntityType entityType) {
        List<String> entityTypes = new ArrayList<>();
        List<Long> **ids** = new ArrayList<>();
```
My questions : 
1-Am I right with my conclusion? 
2-Does the id in STA have to be long data type ?

Any help will be appreciated. 
Thanks

**Comment by hylkevds** [comment]
Yes, currently the test suite assumes all IDs are Long.
I had already reported this in #40.
In the mean time, you can use heavily extended version of the test suite: https://github.com/FraunhoferIOSB/ets-sta10

**Comment by Abouzeid** [comment]
Currently, I'm using the Testing Website: [](http://cite.opengeospatial.org/teamengine/)

Now, if I want to use the **Fraunhofer** test suite, then I need to install and run the **team-engine** servlet. Is that it? 

Lastly, could you please tell me, when are we expecting this issue to be fixed?
Thanks

**Comment by dstenger** [comment]
@taniakhalafbeigi 
Can you estimate when this issue can be fixed?

@hylkevds 
You already provided a pull request to fix this, right?

**Comment by hylkevds** [comment]
You can just run the tests from your own machine with
`java -jar jarfile.jar  test-run-props.xml`

**Comment by dstenger** [comment]
@taniakhalafbeigi What is the current status of this issue?

**Comment by ghobona** [comment]
Closing this issue because it duplicates Issue https://github.com/opengeospatial/ets-sta10/issues/40
