### ISSUE TITLE
Add detailed error messages

### ISSUE THREAD

**Issue by taniakhalafbeigi** [opengeospatial/ets-sta10#44]
Currently the error messages does not have the URL to the failed request. If this URL is added to the message, it will be much easier for users to find the cause of a failed test.

**Comment by dstenger** [comment]
@taniakhalafbeigi Are you working on a solution for this?
If not, Keshav can support you with implementation.

**Comment by taniakhalafbeigi** [comment]
@dstenger I am currently having other issues and PRs in my stack. If Keshav can help with refining the returned error messages, that will be really helpful. 
Thanks a lot, I really appreciate it.

**Comment by keshav-nangare** [comment]
@taniakhalafbeigi 

Can you please review this PR #46? Let me know if you have any changes.

**Comment by taniakhalafbeigi** [comment]
@keshav-nangare Thanks a lot for you contribution. Your PR looks good.
We are looking for detailed error messages for all of our tests. Do you have time to help us with that? Basically we want to do the same thing as you did for PR #46, but for all the tests.

**Comment by keshav-nangare** [comment]
@taniakhalafbeigi 

I have did the same changes for the tests and pushed into same branch(PR #46).

**Comment by taniakhalafbeigi** [comment]
Thanks a lot @keshav-nangare. Great, thanks a lot. I will take a look later and hopefully we will merge it  and have better error messages :tada:
