### ISSUE TITLE
Expecting data on Location(id)/Things

### ISSUE THREAD

**Issue by mariakrommyda** [opengeospatial/ets-sta10#45]
Hello everyone, 

I just got the test 
http://147.102.5.93:8090/SensorThing/v1.0/Things(15)/HistoricalLocations(152)/Locations(150)/Things 
failed at org.opengis.cite.sta10.sensingCore.Capability1Tests.readRelatedEntity(Capability1Tests.java:290) as it returned an empty array:
> { "value":[] }

Based on my understanding of the standard, locations can have 0 to many Things, so the empty response should be an acceptable one. 
The problem can be easily avoided if the test data do not include more than one HistoricalLocation for each Thing, but still I feel that this is not the expected behavior. 

Have I missed something about the correct response and its format or this is an overlook of the test suit?

Best regards, 
Maria.

**Comment by hylkevds** [comment]
The test suite assumes the entities on the server are the ones described in the Preconditions on the page: http://opengeospatial.github.io/ets-sta10/ (also listed below)

The test suite wants to test many possible relations. It can only do that if those relations actually exist. Technically, an empty server is completely standards conform, but the suite can not actually do any tests on an empty server.
One could argue that the suite itself should create the entities it needs to test, but then the read tests would depend on a correct implementation of the write functionality, as explained in #3 

That expected set of entities is the set generated when posting:
```
{
	"description": "thing 1",
	"name": "thing name 1",
	"properties": {
		"reference": "first"
	},
	"Locations": [{
			"description": "location 1",
			"name": "location name 1",
			"location": {
				"type": "Point",
				"coordinates": [-117.05, 51.05]
			},
			"encodingType": "application/vnd.geo+json"
		}],
	"Datastreams": [{
			"unitOfMeasurement": {
				"name": "Lumen",
				"symbol": "lm",
				"definition": "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html/Lumen"
			},
			"description": "datastream 1",
			"name": "datastream name 1",
			"observationType": "http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_Measurement",
			"ObservedProperty": {
				"name": "Luminous Flux",
				"definition": "http://www.qudt.org/qudt/owl/1.0.0/quantity/Instances.html/LuminousFlux",
				"description": "observedProperty 1"
			},
			"Sensor": {
				"description": "sensor 1",
				"name": "sensor name 1",
				"encodingType": "application/pdf",
				"metadata": "Light flux sensor"
			},
			"Observations": [{
					"phenomenonTime": "2015-03-03T00:00:00Z",
					"result": 3
				}, {
					"phenomenonTime": "2015-03-04T00:00:00Z",
					"result": 4
				}]
		}, {
			"unitOfMeasurement": {
				"name": "Centigrade",
				"symbol": "C",
				"definition": "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html/Lumen"
			},
			"description": "datastream 2",
			"name": "datastream name 2",
			"observationType": "http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_Measurement",
			"ObservedProperty": {
				"name": "Tempretaure",
				"definition": "http://www.qudt.org/qudt/owl/1.0.0/quantity/Instances.html/Tempreture",
				"description": "observedProperty 2"
			},
			"Sensor": {
				"description": "sensor 2",
				"name": "sensor name 2",
				"encodingType": "application/pdf",
				"metadata": "Tempreture sensor"
			},
			"Observations": [{
					"phenomenonTime": "2015-03-05T00:00:00Z",
					"result": 5
				}, {
					"phenomenonTime": "2015-03-06T00:00:00Z",
					"result": 6
				}]
		}]
}
```

**Comment by mariakrommyda** [comment]
I understand the limitations, I was just expecting the Core test to run to a 'live' Database and not require a specific one, given that it does not modify the content.

Thanks for the response, 
Maria.
