### ISSUE TITLE
Issues implementing the STA in ASP.NET Core

### ISSUE THREAD

**Issue by crussman** [opengeospatial/ets-sta10#49]
Greetings!

 I must disturb you with an issue I'm experiecing with TEAM Engine.
I'm not sure if it's a problem in the test suite, or related with the
Microsoft technologies. Anyway, I'll try to explain you what's the
problem.
The test suit receives an URL to an API to test (My STA
implementation), which in the start point, it's an OData service
document, basically, a JSON document which has the link to the
metadata of the Entity Data Model, and the entity sets contained in
the API (Datastreams, Things, Sensors, etc...) with three properties
for every one (Name, Kind, and Url), it looks like:

{
"@odata.context": "http://localhost/46967/v1/$metadata",
"value": [
{
"name": "Datastreams",
"kind": "EntitySet",
"url": "Datastreams"
},
{
"name": "Sensors",
"kind": "EntitySet",
"url": "Sensors"
},
{
"name": "Things",
"kind": "EntitySet",
"url": "Things"
},
{
"name": "Locations",
"kind": "EntitySet",
"url": "Locations"
},
{
"name": "HistoricalLocations",
"kind": "EntitySet",
"url": "HistoricalLocations"
},
{
"name": "FeaturesOfInterest",
"kind": "EntitySet",
"url": "FeaturesOfInterest"
},
{
"name": "Observations",
"kind": "EntitySet",
"url": "Observations"
},
{
"name": "ObservedProperties",
"kind": "EntitySet",
"url": "ObservedProperties"
}
]
}

So, when the tests starts running, it checks this document to has this
format, then, it starts checking every entity Set (Datastreams,
Things, Sensors, etc...) and the problem is when it tries to analyze
the URL property, because, according to the source code of the test,
for the Datastreams entity for example, this:

case "Datastreams":
Assert.assertEquals(nameUrl, rootUri + "/Datastreams");

it basically says
something like "If 'nameUrl'(The url property of the document which
has the "Datastreams" value in this case) is equal to 'rootUri'(The
url of my STA implementation) plus the entity name 'Datastreams', it's
true and pass this test step". But the problem is that, it won't
return true because "http://localhost/46967/v1/Datastreams" isn't
equal to "Datastreams". So I found a way to customize the "url"
property in the service document so it can be
"http://localhost/46967/v1/Datastreams" instead of "Datastreams" and
it's accomplishing the condition, but it isn't possible to give that
value to that property in ASP.NET without getting the app crash.

Regards!

**Comment by taniakhalafbeigi** [comment]
Hi,

The rootURI that the test suit expects should be compliant to SensorThings API. You can see an example of how it should look here: http://docs.opengeospatial.org/is/15-078r6/15-078r6.html#36

SensorThings is using OData but it is not following all the stuff, for example there is not /$metadata in SensorThings for now.

**Comment by dstenger** [comment]
@crussman Does this answer your question? If this is the case, can you please close the issue?
