### ISSUE TITLE
GeoJSON encoding type

### ISSUE THREAD

**Issue by hylkevds** [opengeospatial/ets-sta10#5]
The encoding type for GeoJSON in the tests is always set to: `http://example.org/location_types#GeoJSON`
Shouldn't that be `application/vnd.geo+json` ?

**Comment by liangsteve** [comment]
Yes.  It should be `application/vnd.geo+json`

**Comment by hylkevds** [comment]
My pull request fixes this as well, next to two invalid json errors.
