### ISSUE TITLE
Cleanup dependencies

### ISSUE THREAD

**Issue by keshavnangare** [opengeospatial/ets-sta10#50]
When running `mvn org.apache.maven.plugins:maven-dependency-plugin:analyze`, I get following warnings:
```
[WARNING] Used undeclared dependencies found:
[WARNING]    org.apache.httpcomponents:httpcore:jar:4.4.1:compile
[WARNING]    org.testng:testng:jar:6.8.21:compile
[WARNING]    xml-apis:xml-apis:jar:1.4.01:compile
[WARNING]    javax.ws.rs:jsr311-api:jar:1.1.1:compile
[WARNING] Unused declared dependencies found:
[WARNING]    org.opengis.cite:schema-utils:jar:1.7:compile
[WARNING]    com.google.inject:guice:jar:3.0:test
```
All used undeclared compile dependencies shall be declared in Maven pom file.
All unused declared dependencies shall be removed from Maven pom file.

**Comment by keshav-nangare** [comment]
I have added used undeclared dependencies and removed unused declared dependencies except for the following dependency.

1. `com.google.inject:guice` is inherited from the parent and unable to exclude it.

Please find changes in #51 PR.
