### ISSUE TITLE
Upgrade json dependency to v20231013

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-sta10#62]

**Comment by hylkevds** [comment]
You can skip 20220924 and directly go to 20230227

**Comment by dstenger** [comment]
Thanks, for the update.

However, we are about to introduce a [TEAM Engine BOM](https://github.com/opengeospatial/teamengine-bom/blob/main/pom.xml) which sets version `20220320`.

Is there, from your standpoint, a good reason why we should go to `20230227`? In that case, the BOM has to be updated.

**Comment by hylkevds** [comment]
The [release notes](https://github.com/stleary/JSON-java/releases) mention recursion fixes when parsing XML. But when you're certain that part of the library is never used it may not matter.

**Comment by dstenger** [comment]
I just checked the dependency and it does not bring any further transitive dependencies. Thus, I propose to update json to `20230227` in the BOM as this update should not have any side effects and introduces security fixes.

**Comment by dstenger** [comment]
Was solved by #66.
